"""

config
2021/5/11 17:37

=========================

INTRODUCTIONS

=========================
"""

_SCREEN_LEFT = 0
_SCREEN_TOP = 40
_SCREEN_WIDTH = 1024
_SCREEN_HEIGHT = 768

_DEFAULT_REGION = (_SCREEN_LEFT, _SCREEN_TOP, _SCREEN_WIDTH, _SCREEN_HEIGHT)

_RESIZE_WIDTH = 80
_RESIZE_HEIGHT = 60

_RESIZE_REGION = (_RESIZE_WIDTH, _RESIZE_HEIGHT)


class ScreenConfig:
    DEFAULT_REGION = _DEFAULT_REGION
    DEFAULT_W = _SCREEN_WIDTH
    DEFAULT_H = _SCREEN_HEIGHT
    RESIZE_REGION = _RESIZE_REGION
    W = _RESIZE_WIDTH
    H = _RESIZE_HEIGHT


KEY_RELEASED = 0
KEY_PRESS_W = 1
KEY_PRESS_S = 2
KEY_PRESS_A = 3
KEY_PRESS_D = 4
KEY_PRESS_WA = 5
KEY_PRESS_WD = 6
KEY_PRESS_SA = 7
KEY_PRESS_SD = 8
KEY_ERROR = -1


class KeyConfig:
    RELEASED = KEY_RELEASED
    W = KEY_PRESS_W
    S = KEY_PRESS_S
    A = KEY_PRESS_A
    D = KEY_PRESS_D
    WA = KEY_PRESS_WA
    WD = KEY_PRESS_WD
    SA = KEY_PRESS_SA
    SD = KEY_PRESS_SD
    ERR = KEY_ERROR

    CMD_PAUSE = 'Pause'
    CMD_QUIT = 'Quit'